# Generated by Django 2.2.13 on 2022-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
