# Generated by Django 2.2.13 on 2022-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_form_form_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='download_url',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
